version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/sonarr:/config
      - ./../frontend/tv:/tv 
      - ./downloads:/downloads 
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - backend-net
      
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/radarr:/config
      - ./../frontend/movies:/movies 
      - ./downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - backend-net

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - backend-net

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/bazarr:/config
      - ./../frontend/movies:/movies 
      - ./../frontend/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - backend-net

  deluge:
        container_name: deluge
        volumes:
            - ./downloads:/download
            - ./config/deluge:/config
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - OPENVPN_PROVIDER=NORDVPN
            - OPENVPN_USERNAME=${VPN_USER}
            - OPENVPN_PASSWORD=${VPN_PASS}
            - NORDVPN_PROTOCOL=tcp
            - NORDVPN_CATEGORY=legacy_p2p
            - NORDVPN_COUNTRY=EE
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - LOCAL_NETWORK=10.0.0.0/24
        cap_add:
            - NET_ADMIN
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1
        ports:
            - '8112:8112'
        image: ebrianne/docker-deluge-openvpn
        networks:
          - backend-net

networks:
  backend-net:
    driver: bridge